name = "DSO"
uuid = "1ecce73e-f1b1-49c8-92b6-7d632d350df1"
authors = ["Sebastian Malkusch"]
version = "0.0.1-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
